--DROP TABLE IF EXISTS UserData;

CREATE TABLE UserData (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  username VARCHAR(250) NOT NULL,
  password VARCHAR(250) NOT NULL,
  role VARCHAR(250) NOT NULL
);

CREATE TABLE Universities (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  uname VARCHAR(250) NOT NULL,
  address VARCHAR(250) NOT NULL
);